<nav id="nav-wrap">

         <a class="mobile-btn" href="#nav-wrap" title="Show navigation">Show navigation</a>
	      <a class="mobile-btn" href="#" title="Hide navigation">Hide navigation</a>

         <ul id="nav" class="nav">
            <li <?=((((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) & (!isset($_GET['goto']) )) ? "class='current'" : "")?>><a class="<?=((isset($_GET['page']) && $_GET['page'] == "accueil") || !isset($_GET['page']) ? "smoothscroll" : "")?>" href="<?=(isset($_GET['page']) && $_GET['page'] == "accueil" || !isset($_GET['page']) ? "#" : "index.php?page=accueil&goto=")?>home" data-trad="entete-nav-home">Home</a></li>
            <li <?=((((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) & (isset($_GET['goto']) & $_GET['goto']=="about" )) ? "class='current'" : "")?>><a class="<?=(((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) ? "smoothscroll" : "")?>" href="<?=(isset($_GET['page']) && $_GET['page'] == "accueil" || !isset($_GET['page']) ? "#" : "index.php?page=accueil&goto=")?>about" data-trad="entete-nav-about">About</a></li>
	        <li <?=((((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) & (isset($_GET['goto']) & $_GET['goto']=="resume" )) ? "class='current'" : "")?>><a class="<?=(((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) ? "smoothscroll" : "")?>" href="<?=(isset($_GET['page']) && $_GET['page'] == "accueil" || !isset($_GET['page']) ? "#" : "index.php?page=accueil&goto=")?>resume" data-trad="entete-nav-resume">Resume</a></li>
            <li <?=((((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) & (isset($_GET['goto']) & $_GET['goto']=="work" )) ? "class='current'" : "")?>><a class="<?=(((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) ? "smoothscroll" : "")?>" href="<?=(isset($_GET['page']) && $_GET['page'] == "accueil" || !isset($_GET['page']) ? "#" : "index.php?page=accueil&goto=")?>work" onclick="resetAnim();" data-trad="entete-nav-works">Works</a></li>
            <li <?=((((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) & (isset($_GET['goto']) & $_GET['goto']=="contact" )) ? "class='current'" : "")?>><a class="<?=(((isset($_GET['page']) & $_GET['page'] == "accueil") || !isset($_GET['page'])) ? "smoothscroll" : "")?>" href="<?=(isset($_GET['page']) && $_GET['page'] == "accueil" || !isset($_GET['page']) ? "#" : "index.php?page=accueil&goto=")?>contact" data-trad="entete-nav-contact">Contact</a></li>
            <li <?=(isset($_GET['page']) && $_GET['page'] == "hobbies" ? "class='current'" : "" ) ?>><a href="index.php?page=hobbies" data-trad="entete-nav-hobbies">Hobbies</a></li>
         </ul> <!-- end #nav -->

      </nav>